import { useState } from 'react';
import { LogIn, Menu, ShipWheel, UserRound, X } from 'lucide-react';
import { api } from './api.js';
import UserApp from './user/UserApp.jsx';
import AdminDashboard from './admin/AdminDashboard.jsx';
import FishermanDashboard from './fisherman/FishermanDashboard.jsx';

export default function App() { const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('tide_user') || 'null')); const [authMode, setAuthMode] = useState(null); const [menu, setMenu] = useState(false); const auth = async form => { const result = authMode === 'login' ? await api.login(form) : await api.register(form); if (result.status === 'pending') throw new Error(result.message); localStorage.setItem('tide_token', result.token); localStorage.setItem('tide_user', JSON.stringify(result.user)); setUser(result.user); setAuthMode(null); }; const logout = () => { localStorage.clear(); setUser(null); }; const rolePage = user?.role === 'admin' ? <AdminDashboard /> : user?.role === 'fisherman' ? <FishermanDashboard /> : <UserApp user={user} onAuth={setAuthMode} />; return <><header className="topbar"><a className="brand" href="/"><span className="brand-mark"><ShipWheel size={20} /></span>Tide<span>Market</span></a><button className="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button><nav className={menu ? 'open' : ''}><a href="#market">Marketplace</a>{user?.role === 'admin' && <a href="#admin">Admin</a>}{user ? <><span className="user-name"><UserRound size={15} /> {user.name}</span><button className="text-button" onClick={logout}>Log out</button></> : <><button className="button dark" onClick={() => setAuthMode('login')}><LogIn size={16} /> Sign in</button><button className="text-button" onClick={() => setAuthMode('register')}>Buyer registration</button></>}</nav></header>{rolePage}{authMode && <AuthModal mode={authMode} onClose={() => setAuthMode(null)} onSwitch={() => setAuthMode(authMode === 'login' ? 'register' : 'login')} onSubmit={auth} />}</>; }
function AuthModal({ mode, onClose, onSwitch, onSubmit }) { const [form, setForm] = useState({}); const [error, setError] = useState(''); const change = e => setForm({ ...form, [e.target.name]: e.target.value }); const submit = e => { e.preventDefault(); onSubmit(form).catch(err => setError(err.message)); }; return <div className="modal-backdrop" onClick={onClose}><div className="modal auth-modal" onClick={e => e.stopPropagation()}><button className="close" onClick={onClose}>×</button><p className="kicker">TIDEMARKET ACCOUNT</p><h2>{mode === 'login' ? 'Welcome back to the water.' : 'Create your buyer account.'}</h2><form onSubmit={submit}>{mode === 'register' && <input name="name" placeholder="Full name" onChange={change} required />}<input name="email" type="email" placeholder="Email address" onChange={change} required /><input name="password" type="password" placeholder="Password" onChange={change} required />{error && <p className="form-error">{error}</p>}<button className="button primary full" type="submit">{mode === 'login' ? 'Sign in' : 'Create buyer account'}</button></form><button className="switch-auth" onClick={onSwitch}>Switch to {mode === 'login' ? 'buyer registration' : 'sign in'}</button></div></div>; }
