import { useEffect, useState } from 'react';
import { CheckCircle2, ClipboardList, Fish, Gavel, ImagePlus, Plus, ShoppingBag, Trash2, XCircle } from 'lucide-react';
import { api } from '../api.js';

const emptyForm = { fishType: '', quantity: '', quality: 'Premium', size: 'Medium', location: '', expectedPrice: '', salePrice: '', description: '', imageUrl: '', saleMode: 'sale', minimumIncrement: 10, endTime: '' };

export default function FishermanDashboard() {
  const [listings, setListings] = useState([]); const [sales, setSales] = useState([]); const [meta, setMeta] = useState({ qualities: [], sizes: [] }); const [form, setForm] = useState(emptyForm); const [mode, setMode] = useState(null); const [view, setView] = useState('inventory'); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const loadListings = () => api.fishermanListings().then(setListings).catch(err => setError(err.message));
  const loadSales = () => api.fishermanSales().then(setSales).catch(err => setError(err.message));
  useEffect(() => { api.meta().then(setMeta).catch(err => setError(err.message)); loadListings(); loadSales(); }, []);
  const updateForm = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  const detectImage = async event => { const file = event.target.files?.[0]; if (!file) return; setError(''); try { const result = await api.detectFish(file); const confidence = (result.prediction.confidence * 100).toFixed(1); setForm(current => ({ ...current, imageUrl: result.imageUrl, fishType: result.prediction.fish, description: `AI detected ${result.prediction.fish} with ${confidence}% confidence. Add freshness and handling notes here.` })); setMessage(`Detected ${result.prediction.fish} (${confidence}% confidence).`); } catch (err) { setError(err.message); } };
  const submit = async event => { event.preventDefault(); setError(''); try { const expectedPrice = mode === 'bid' ? Number(form.expectedPrice) : Number(form.salePrice); const listing = await api.createListing({ ...form, saleMode: mode, expectedPrice, salePrice: Number(form.salePrice || expectedPrice), quantity: Number(form.quantity) }); if (mode === 'bid') await api.createAuction(listing.id, { startPrice: expectedPrice, minimumIncrement: Number(form.minimumIncrement), startTime: new Date().toISOString(), endTime: new Date(form.endTime).toISOString() }); setMessage(mode === 'bid' ? 'Bidding listing created.' : 'Sale listing created.'); setForm(emptyForm); setMode(null); setView('inventory'); loadListings(); } catch (err) { setError(err.message); } };
  const closeBid = async id => { try { await api.closeAuction(id); setMessage('Bidding stopped. The winning buyer can checkout.'); loadListings(); loadSales(); } catch (err) { setError(err.message); } };
  const deleteListing = async id => { if (!window.confirm('Delete this fish listing?')) return; try { await api.deleteListing(id); setMessage('Listing deleted.'); loadListings(); } catch (err) { setError(err.message); } };
  const startPost = () => { setForm(emptyForm); setMode(null); setView('inventory'); };
  return <main className="dashboard fisherman-view"><div className="dashboard-heading"><div><p className="kicker">FISHERMAN DECK</p><h1>Your catch, your terms.</h1><p>Manage your catch, buyer orders, and completed sales.</p></div><button className="button primary" onClick={startPost}><Plus size={17} /> Post a catch</button></div>{message && <p className="success-notice"><CheckCircle2 size={16} /> {message}</p>}{error && <p className="notice"><XCircle size={16} /> {error}</p>}<div className="fisherman-tabs"><button className={view === 'inventory' ? 'active' : ''} onClick={() => setView('inventory')}><Fish size={17} /> Inventory <b>{listings.length}</b></button><button className={view === 'orders' ? 'active' : ''} onClick={() => { setView('orders'); loadSales(); }}><ClipboardList size={17} /> Buyer orders <b>{sales.length}</b></button><button className={view === 'sales' ? 'active' : ''} onClick={() => { setView('sales'); loadSales(); }}><ShoppingBag size={17} /> Selling data <b>{sales.filter(order => order.paymentStatus === 'paid' || ['processing', 'completed', 'delivered'].includes(order.orderStatus)).length}</b></button></div>{view === 'orders' && <OrdersPage orders={sales} />}{view === 'sales' && <SalesPage orders={sales} />}{view === 'inventory' && <>{mode ? <ListingForm mode={mode} form={form} meta={meta} onChange={updateForm} onImage={detectImage} onSubmit={submit} onBack={() => setMode(null)} /> : <SellChoice onChoose={value => { setForm({ ...emptyForm, saleMode: value }); setMode(value); }} /> }<section className="catch-list"><div className="panel-title"><h2>Your fish inventory</h2><span>{listings.length} catches</span></div>{listings.map(item => <CatchRow key={item.id} item={item} onClose={closeBid} onDelete={deleteListing} />)}{!listings.length && <p className="empty">No fish posted yet.</p>}</section></>}</main>;
}

function SellChoice({ onChoose }) { return <section className="sell-choice"><button className="mode-card" onClick={() => onChoose('sale')}><ShoppingBag size={30} /><strong>Sell at a fixed price</strong><small>Buyers can purchase this fish directly.</small></button><button className="mode-card" onClick={() => onChoose('bid')}><Gavel size={30} /><strong>Open for bidding</strong><small>Buyers compete and increase the price.</small></button></section>; }
function ListingForm({ mode, form, meta, onChange, onImage, onSubmit, onBack }) { return <section className="panel listing-page"><button className="back-button" type="button" onClick={onBack}>← Back to selling options</button><p className="kicker">{mode === 'bid' ? 'BID LISTING' : 'SALE LISTING'}</p><h2>{mode === 'bid' ? 'Create a bidding listing.' : 'Create a fixed-price listing.'}</h2><form onSubmit={onSubmit}><label className="upload-field"><ImagePlus size={18} /> Upload fish image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={onImage} required={!form.imageUrl} /></label>{form.imageUrl && <img className="upload-preview" src={form.imageUrl} alt="Detected fish" />}<div className="form-grid"><input name="fishType" value={form.fishType} onChange={onChange} placeholder="Detected fish name" required /><select name="quality" value={form.quality} onChange={onChange}>{meta.qualities.map(value => <option key={value}>{value}</option>)}</select><select name="size" value={form.size} onChange={onChange}>{meta.sizes.map(value => <option key={value}>{value}</option>)}</select><input name="quantity" type="number" min="1" placeholder="Quantity (kg)" value={form.quantity} onChange={onChange} required /><input name="location" placeholder="Landing port" value={form.location} onChange={onChange} required />{mode === 'bid' ? <input name="expectedPrice" type="number" min="1" placeholder="Initial bid price / kg" value={form.expectedPrice} onChange={onChange} required /> : <input name="salePrice" type="number" min="1" placeholder="Sale price / kg" value={form.salePrice} onChange={onChange} required />}</div>{mode === 'bid' && <div className="form-grid"><input name="minimumIncrement" type="number" min="1" placeholder="Minimum bid increase" value={form.minimumIncrement} onChange={onChange} required /><input name="endTime" type="datetime-local" value={form.endTime} onChange={onChange} required /></div>}<textarea name="description" placeholder="Fish details and freshness notes" value={form.description} onChange={onChange} /><button className="button primary" type="submit">Publish {mode === 'bid' ? 'bidding' : 'sale'} listing</button></form></section>; }
function CatchRow({ item, onClose, onDelete }) { const auction = item.auction; const canDelete = item.status === 'available' && !auction; return <article className="catch-row">{item.imageUrl ? <img src={item.imageUrl} alt={item.fishType} /> : <div className="catch-placeholder"><Fish size={30} /></div>}<div className="catch-main"><div className="card-row"><h3>{item.fishType}</h3><span className="quality">{item.saleMode === 'bid' ? 'BID' : 'SALE'}</span></div><p>{item.quantity} kg · {item.quality} · {item.location}</p>{item.saleMode === 'bid' && auction ? <div className="live-price">Initial ₹{auction.startPrice} · Current ₹{auction.currentPrice || auction.startPrice} · <b>+{auction.priceIncreasePercent || 0}%</b></div> : <div className="live-price">Fixed sale ₹{item.salePrice || item.expectedPrice}/kg</div>}<div className="verification">{item.imageVerification === 'verified' ? <><CheckCircle2 size={14} /> AI image verified</> : <><ImagePlus size={14} /> Image verification pending</>}</div></div><div className="catch-side"><strong>₹{item.saleMode === 'bid' ? auction?.currentPrice || item.expectedPrice : item.salePrice || item.expectedPrice}<small>/kg</small></strong>{item.saleMode === 'bid' && item.status === 'auction' && <button className="button small dark" onClick={() => onClose(auction.id)}>Stop bidding</button>}{canDelete && <button className="icon-button danger" title="Delete listing" onClick={() => onDelete(item.id)}><Trash2 size={17} /></button>}</div></article>; }
function OrdersPage({ orders }) { return <section className="panel fisherman-data"><div className="panel-title"><h2>Orders from buyers</h2><span>{orders.length} orders</span></div>{orders.map(order => <OrderRow key={order.id} order={order} />)}{!orders.length && <p className="empty">No buyer orders yet.</p>}</section>; }
function SalesPage({ orders }) { const completed = orders.filter(order => order.paymentStatus === 'paid' || ['processing', 'completed', 'delivered'].includes(order.orderStatus)); const total = completed.reduce((sum, order) => sum + Number(order.amount || 0), 0); return <section className="panel fisherman-data"><div className="panel-title"><h2>Selling data</h2><span>Total ₹{total.toLocaleString()}</span></div>{completed.map(order => <OrderRow key={order.id} order={order} sale />)}{!completed.length && <p className="empty">Sold fish will appear here after a buyer creates an order.</p>}</section>; }
function OrderRow({ order, sale = false }) { const listing = order.listingDetails; return <article className="order-row">{listing?.imageUrl ? <img src={listing.imageUrl} alt={listing.fishType} /> : <div className="catch-placeholder"><Fish size={22} /></div>}<div><strong>{listing?.fishType || 'Fish order'}</strong><small>Order {order.orderNumber || order.id}</small><small>{order.quantity || listing?.quantity || 0} kg · Buyer order · {new Date(order.createdAt).toLocaleDateString()}</small></div><div className="order-amount"><strong>₹{Number(order.amount || 0).toLocaleString()}</strong><small className={sale ? 'status-paid' : ''}>{order.orderStatus || 'pending'}</small></div></article>; }