import { useEffect, useState } from 'react';
import { Activity, Anchor, ArrowLeft, ClipboardList, CircleDollarSign, Fish, UserPlus, Users } from 'lucide-react';
import { api } from '../api.js';

export default function AdminDashboard() {
  const [view, setView] = useState('fishermen');
  const [data, setData] = useState(null);
  const [users, setUsers] = useState([]);
  const [requests, setRequests] = useState([]);
  const [selected, setSelected] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const load = () => Promise.all([api.adminOverview(), api.adminUsers(), api.registrationRequests()])
    .then(([overview, people, pending]) => { setData(overview); setUsers(people); setRequests(pending); })
    .catch(err => setError(err.message));
  useEffect(() => { load(); }, []);
  const fishermen = users.filter(person => person.role === 'fisherman');
  const review = async (id, action) => { try { const result = action === 'accept' ? await api.acceptRegistration(id) : await api.rejectRegistration(id); setMessage(result.message || `Request ${action}ed.`); load(); } catch (err) { setError(err.message); } };
  const openFisherman = async person => { setError(''); try { setSelected(await api.adminFisherman(person.id)); } catch (err) { setError(err.message); } };
  const counts = data?.counts || {};

  if (selected) return <FishermanDetail data={selected} onBack={() => setSelected(null)} />;
  return <main className="dashboard admin-view"><div className="dashboard-heading"><div><p className="kicker">COMMAND CENTER</p><h1>Good morning, admin.</h1><p>Manage the people and activity on TideMarket.</p></div><div className="admin-actions"><span className="live-tag"><span className="pulse" /> SYSTEMS LIVE</span><button className="button primary" onClick={() => setShowForm(true)}><UserPlus size={16} /> Create fisherman</button></div></div>{message && <p className="success-notice">{message}</p>}{error && <p className="notice">{error}</p>}<div className="metrics"><Metric icon={<Users />} label="Registered users" value={counts.users ?? '—'} /><Metric icon={<Anchor />} label="Active listings" value={counts.listings ?? '—'} /><Metric icon={<Activity />} label="Total bids" value={counts.bids ?? '—'} /><Metric icon={<CircleDollarSign />} label="Paid volume" value={data ? `₹${(data.paidTotal || 0).toLocaleString()}` : '—'} /></div><div className="admin-tabs"><button className={view === 'fishermen' ? 'active' : ''} onClick={() => setView('fishermen')}><Fish size={18} /> Fishermen <b>{fishermen.length}</b></button><button className={view === 'requests' ? 'active' : ''} onClick={() => setView('requests')}><ClipboardList size={18} /> Buyer requests <b>{requests.length}</b></button></div>{view === 'fishermen' ? <section className="panel admin-page"><div className="panel-title"><h2>Fisherman details</h2><span>Click a fisherman to inspect sales</span></div>{fishermen.map(person => <button className="person-line person-button" key={person.id} onClick={() => openFisherman(person)}><div className="avatar">{person.name[0]}</div><div><strong>{person.name}</strong><small>{person.email} · {person.location || 'Location not set'}</small></div><span className="role">View details</span></button>)}{!fishermen.length && <p className="empty">No fishermen created yet.</p>}</section> : <section className="panel admin-page"><div className="panel-title"><h2>Buyer registration requests</h2><span>{requests.length} pending</span></div>{requests.map(request => <div className="request-line" key={request.id}><div><strong>{request.name}</strong><small>{request.email}{request.phone ? ` · ${request.phone}` : ''}</small></div><div className="request-actions"><button className="button small primary" onClick={() => review(request.id, 'accept')}>Accept</button><button className="button small secondary" onClick={() => review(request.id, 'reject')}>Reject</button></div></div>)}{!requests.length && <p className="empty">No buyer registration requests.</p>}</section>}{showForm && <FishermanForm onClose={() => setShowForm(false)} onCreated={name => { setShowForm(false); setMessage(`${name} can now sign in as a fisherman.`); load(); }} />}</main>;
}

function FishermanDetail({ data, onBack }) { return <main className="dashboard admin-view"><button className="back-button" onClick={onBack}><ArrowLeft size={16} /> Back to admin</button><div className="dashboard-heading detail-heading"><div><p className="kicker">FISHERMAN PROFILE</p><h1>{data.fisherman.name}</h1><p>{data.fisherman.email} · {data.fisherman.location || 'Location not set'}</p></div></div><div className="metrics"><Metric icon={<Fish />} label="Fish posted" value={data.listings.length} /><Metric icon={<CircleDollarSign />} label="Total gained" value={`₹${Number(data.totalGained || 0).toLocaleString()}`} /><Metric icon={<Activity />} label="Sold catches" value={data.listings.filter(item => item.saleAmount > 0).length} /></div><section className="panel admin-page"><div className="panel-title"><h2>Fish sold and earnings</h2><span>Bid and sale history</span></div>{data.listings.map(item => <div className="sale-line" key={item.id}>{item.imageUrl ? <img src={item.imageUrl} alt={item.fishType} /> : <div className="catch-placeholder"><Fish size={22} /></div>}<div><strong>{item.fishType}</strong><small>{item.quantity} kg · {item.quality} · {item.location}</small><small>{item.bids} bids · highest bid ₹{item.highestBid.toLocaleString()}</small></div><div className="sale-amount"><strong>₹{item.saleAmount.toLocaleString()}</strong><small>{item.saleStatus}</small></div></div>)}{!data.listings.length && <p className="empty">This fisherman has not posted any fish.</p>}</section></main>; }
function Metric({ icon, label, value }) { return <div className="metric"><span className="metric-icon">{icon}</span><span>{label}</span><strong>{value}</strong></div>; }
function FishermanForm({ onClose, onCreated }) { const [form, setForm] = useState({}); const [error, setError] = useState(''); const change = event => setForm({ ...form, [event.target.name]: event.target.value }); const submit = event => { event.preventDefault(); api.createFisherman(form).then(result => onCreated(result.name)).catch(err => setError(err.message)); }; return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={onClose}>×</button><p className="kicker">ADMIN ACCOUNT CONTROL</p><h2>Create fisherman login.</h2><form onSubmit={submit}><input name="name" placeholder="Fisherman name" onChange={change} required /><input name="email" type="email" placeholder="Login email" onChange={change} required /><input name="password" placeholder="Temporary password" onChange={change} required /><input name="location" placeholder="Port or location" onChange={change} /><input name="phone" placeholder="Phone number" onChange={change} />{error && <p className="form-error">{error}</p>}<button className="button primary full" type="submit">Create fisherman account</button></form></div></div>; }
